import { gonka } from "../client";
import { parseGonkaJson } from "../responseParser";
import { runAcrossModels } from "../multiModel";
import { GONKA_MODELS } from "../models";

/* ============================================================
   TYPES
   ============================================================ */

export type ExperienceLevel =
  | "Beginner"
  | "Intermediate"
  | "Expert";

export type ProjectComplexity =
  | "Simple"
  | "Moderate"
  | "Complex"
  | "Highly Complex";

export type BudgetAssessment =
  | "REASONABLE"
  | "POSSIBLY_LOW"
  | "POSSIBLY_HIGH"
  | "UNKNOWN";

export type TimelineAssessment =
  | "REASONABLE"
  | "POSSIBLY_TOO_SHORT"
  | "POSSIBLY_TOO_LONG"
  | "UNKNOWN";

export type VerificationStatus = "PASS" | "FAIL";
export type VerificationResolutionMethod =
  | "CONSENSUS"
  | "MAJORITY"
  | "REJECTED";

export interface ProjectBudget {
  amount: number;
  currency: string;
}

export interface ProjectTimeline {
  days: number;
}

export interface ProjectAssistantRequirements {
  projectTitle: string;
  description: string;
  coreFeatures: string[];
  targetUsers?: string[];
  platform?: string;
  budget: ProjectBudget;
  timeline: ProjectTimeline;
}

/**
 * The ONE project structure generated by the primary analysis model.
 */
export interface ProjectMilestone {
  title: string;
  description: string;
  percentageAllocation: number;
  amount: number;
}

export interface ProjectAnalysis {
  projectTitle: string;
  projectDescription: string;
  projectType: string;
  platform: string | null;
  targetUsers: string[];
  coreFeatures: string[];
  complexity: ProjectComplexity;
  requiredSkills: string[];
  experienceLevel: ExperienceLevel;
  keyDeliverables: string[];
  technicalConsiderations: string[];
  budget: ProjectBudget;
  budgetAssessment: BudgetAssessment;
  estimatedTimelineDays: number;
  timelineAssessment: TimelineAssessment;
  milestones: ProjectMilestone[];
}

export interface ProjectAnalysisModelResult {
  model: string;
  analysis: ProjectAnalysis;
  confidence: "LOW" | "MEDIUM" | "HIGH";
  reasoning: string;
  requestId: string;
}

/**
 * Each verifier receives the SAME primary analysis and judges it.
 * Verifiers do NOT create alternative project analyses.
 */
export interface ProjectAnalysisVerificationResult {
  model: string;
  status: VerificationStatus;
  confidence: "LOW" | "MEDIUM" | "HIGH";
  issues: string[];
  checks: {
    requirementsAlignment: boolean;
    structureValidity: boolean;
    milestoneValidity: boolean;
    milestoneUniqueness: boolean;
    allocationValidity: boolean;
    budgetTimelinePreserved: boolean;
    completeness: boolean;
  };
  reasoning: string;
  requestId: string;
}

export interface ProjectAnalysisVerification {
  status: VerificationStatus;
  passedCount: number;
  failedCount: number;
  totalModels: number;
  confidence: "LOW" | "MEDIUM" | "HIGH";
  resolutionMethod: VerificationResolutionMethod;
  verifierResults: ProjectAnalysisVerificationResult[];
  reasoning: string;
}

export interface ProjectAnalysisResult {
  analysis: ProjectAnalysis;
  verification: ProjectAnalysisVerification;

  primaryRequestId: string;

  verifierRequestIds: {
    model: string;
    requestId: string;
  }[];

  successfulModels: number;
  failedModels: number;
}

/* ============================================================
   PRIMARY MODEL PROMPT
   ============================================================ */

function buildProjectAnalysisPrompt(
  requirements: ProjectAssistantRequirements,
): string {
  return `
You are TrustHire's PRIMARY Project Analysis AI.

The Project Assistant has already spoken with the client and confirmed the client's requirements.

Your job is to analyse those confirmed requirements and create ONE complete, structured project specification for TrustHire and potential freelancers.

You are the PRIMARY ANALYSIS MODEL.
Create the complete project structure yourself.

You are NOT the Project Assistant.
Do not continue the conversation with the client.
Do not ask questions.
Do not change the client's approved budget or timeline.
Do not invent client requirements.

============================================================
CONFIRMED CLIENT REQUIREMENTS
============================================================

${JSON.stringify(requirements, null, 2)}

============================================================
YOUR RESPONSIBILITY
============================================================

Analyse the confirmed project and determine:
1. Project type
2. Freelancer-facing project description
3. Platform
4. Target users
5. Core features
6. Project complexity ("Simple" | "Moderate" | "Complex" | "Highly Complex")
7. Required skills (technical skills for freelancer matching)
8. Recommended experience level ("Beginner" | "Intermediate" | "Expert")
9. Key deliverables
10. Technical considerations
11. Budget assessment
12. Timeline assessment
13. A practical milestone breakdown

============================================================
MILESTONE REQUIREMENTS
============================================================

Create between 2 and 6 milestones, preferably 3 to 5.

Milestones must represent DISTINCT development phases.

Good examples:
- Design & Architecture
- Core Development
- Integration & Features
- Testing, QA & Deployment

IMPORTANT:
- Do NOT create duplicate milestones representing the same work.
- Each milestone must have a distinct purpose and meaningful scope.
- Different milestones may belong to the same broad development stage if they
  represent genuinely different work (for example, Authentication and Payment
  Integration are different milestones).
- The milestones must cover the project's actual work from start to completion.
- Each milestone must have a clear title and description.
- percentageAllocation must be an integer from 1 to 100.
- All percentage allocations MUST sum to exactly 100.
- Do NOT calculate money amounts. TrustHire calculates the amounts from the approved budget.
- Do NOT change the client's approved budget or timeline.

============================================================
OUTPUT FORMAT
============================================================

Return ONLY valid JSON.
Do NOT use markdown code fences.
Do NOT include <think> tags.

{
  "projectTitle": "${requirements.projectTitle}",
  "projectDescription": "Professional freelancer-facing description",
  "projectType": "e.g. Web Application / E-commerce",
  "platform": "e.g. Web / Mobile / Full-Stack",
  "targetUsers": ["string"],
  "coreFeatures": ["string"],
  "complexity": "Moderate",
  "requiredSkills": ["string"],
  "experienceLevel": "Intermediate",
  "keyDeliverables": ["string"],
  "technicalConsiderations": ["string"],
  "budget": {
    "amount": ${requirements.budget.amount},
    "currency": "${requirements.budget.currency}"
  },
  "budgetAssessment": "REASONABLE",
  "estimatedTimelineDays": ${requirements.timeline.days},
  "timelineAssessment": "REASONABLE",
  "milestones": [
    {
      "title": "Design & Architecture",
      "description": "System architecture, UI wireframes, database schema, and project setup.",
      "percentageAllocation": 30
    },
    {
      "title": "Core Development",
      "description": "Implement the main application features and business logic.",
      "percentageAllocation": 45
    },
    {
      "title": "Testing, QA & Deployment",
      "description": "Testing, bug fixes, security checks, deployment, and documentation.",
      "percentageAllocation": 25
    }
  ],
  "confidence": "HIGH",
  "reasoning": "Brief explanation of the analysis."
}
`.trim();
}

/* ============================================================
   VALIDATION HELPERS
   ============================================================ */

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((item) => typeof item === "string");
}

function isValidPercentage(value: unknown): value is number {
  return (
    typeof value === "number" &&
    Number.isFinite(value) &&
    Number.isInteger(value) &&
    value >= 1 &&
    value <= 100
  );
}

type MilestoneStage =
  | "PLANNING_DESIGN"
  | "CORE_DEVELOPMENT"
  | "INTEGRATION_FEATURES"
  | "TESTING_DEPLOYMENT";

function normalise(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/\s+/g, " ");
}

function classifyMilestoneStage(
  title: string,
  description: string,
): MilestoneStage {
  const text = `${title} ${description}`.toLowerCase();

  if (
    text.includes("test") ||
    text.includes("qa") ||
    text.includes("deploy") ||
    text.includes("launch") ||
    text.includes("handover") ||
    text.includes("documentation")
  ) {
    return "TESTING_DEPLOYMENT";
  }

  if (
    text.includes("payment") ||
    text.includes("gateway") ||
    text.includes("auth") ||
    text.includes("integration") ||
    text.includes("admin") ||
    text.includes("notification") ||
    text.includes("smart contract") ||
    text.includes("escrow")
  ) {
    return "INTEGRATION_FEATURES";
  }

  if (
    text.includes("design") ||
    text.includes("architecture") ||
    text.includes("wireframe") ||
    text.includes("spec") ||
    text.includes("planning") ||
    text.includes("setup") ||
    text.includes("prototype")
  ) {
    return "PLANNING_DESIGN";
  }

  return "CORE_DEVELOPMENT";
}

interface RawMilestone {
  title: string;
  description: string;
  percentageAllocation: number;
}

/**
 * Deterministic safety validation BEFORE the multi-model verification.
 *
 * This does not replace multi-model verification.
 * It only prevents structurally invalid primary output. Semantic duplicate
 * detection is intentionally handled by the independent verifier models.
 */
function validateMilestones(value: unknown): RawMilestone[] {
  if (!Array.isArray(value)) {
    throw new Error("Invalid milestones format");
  }

  if (value.length < 2 || value.length > 6) {
    throw new Error("Milestones must contain between 2 and 6 items");
  }

  const milestones = value.map((item, index) => {
    if (!item || typeof item !== "object") {
      throw new Error(`Invalid milestone at index ${index}`);
    }

    const data = item as Record<string, unknown>;

    if (typeof data.title !== "string" || !data.title.trim()) {
      throw new Error(`Invalid milestone title at index ${index}`);
    }

    if (typeof data.description !== "string" || !data.description.trim()) {
      throw new Error(`Invalid milestone description at index ${index}`);
    }

    if (!isValidPercentage(data.percentageAllocation)) {
      throw new Error(`Invalid milestone percentage at index ${index}`);
    }

    return {
      title: data.title.trim(),
      description: data.description.trim(),
      percentageAllocation: data.percentageAllocation,
    };
  });

  const total = milestones.reduce(
    (sum, milestone) => sum + milestone.percentageAllocation,
    0,
  );

  if (total !== 100) {
    throw new Error(
      `Milestone percentages must total exactly 100. Received ${total}`,
    );
  }

  /*
   * IMPORTANT:
   * Do NOT reject milestones merely because they belong to the same broad
   * development stage.
   *
   * For example:
   *   - Authentication & User Management
   *   - Payment Gateway Integration
   *
   * can both be integration-related while still being two legitimate,
   * different milestones.
   *
   * Genuine duplicate milestone detection is delegated to the independent
   * MiniMax + DeepSeek verification stage, where the models can understand
   * the semantic purpose of each milestone.
   *
   * We only perform basic structural validation here.
   */

  return milestones;
}

/**
 * Converts AI-generated percentages into exact currency amounts.
 * Uses the Largest Remainder Method to prevent rounding loss.
 */
export function calculateMilestoneAmounts(
  milestones: RawMilestone[],
  budget: ProjectBudget,
): ProjectMilestone[] {
  const totalCents = Math.round(budget.amount * 100);

  const exactAmounts = milestones.map(
    (milestone) =>
      (totalCents * milestone.percentageAllocation) / 100,
  );

  const amounts = exactAmounts.map((amount) => Math.floor(amount));

  let remaining =
    totalCents - amounts.reduce((sum, amount) => sum + amount, 0);

  const remainderOrder = exactAmounts
    .map((exact, index) => ({
      index,
      fraction: exact - amounts[index],
    }))
    .sort((a, b) => b.fraction - a.fraction);

  for (const item of remainderOrder) {
    if (remaining <= 0) break;
    amounts[item.index] += 1;
    remaining -= 1;
  }

  return milestones.map((milestone, index) => ({
    title: milestone.title,
    description: milestone.description,
    percentageAllocation: milestone.percentageAllocation,
    amount: amounts[index] / 100,
  }));
}

/* ============================================================
   ANALYSIS VALIDATION
   ============================================================ */

function validateAnalysis(
  value: unknown,
  requirements: ProjectAssistantRequirements,
): ProjectAnalysis {
  if (!value || typeof value !== "object") {
    throw new Error("Project analysis is not an object");
  }

  const data = value as Record<string, unknown>;

  if (typeof data.projectTitle !== "string") {
    throw new Error("Invalid projectTitle");
  }

  if (typeof data.projectDescription !== "string") {
    throw new Error("Invalid projectDescription");
  }

  if (typeof data.projectType !== "string") {
    throw new Error("Invalid projectType");
  }

  if (data.platform !== null && typeof data.platform !== "string") {
    throw new Error("Invalid platform");
  }

  if (!isStringArray(data.targetUsers)) {
    throw new Error("Invalid targetUsers");
  }

  if (!isStringArray(data.coreFeatures)) {
    throw new Error("Invalid coreFeatures");
  }

  const validComplexities: ProjectComplexity[] = [
    "Simple",
    "Moderate",
    "Complex",
    "Highly Complex",
  ];

  if (!validComplexities.includes(data.complexity as ProjectComplexity)) {
    throw new Error("Invalid complexity");
  }

  if (!isStringArray(data.requiredSkills)) {
    throw new Error("Invalid requiredSkills");
  }

  const validExperienceLevels: ExperienceLevel[] = [
    "Beginner",
    "Intermediate",
    "Expert",
  ];

  if (
    !validExperienceLevels.includes(
      data.experienceLevel as ExperienceLevel,
    )
  ) {
    throw new Error("Invalid experienceLevel");
  }

  if (!isStringArray(data.keyDeliverables)) {
    throw new Error("Invalid keyDeliverables");
  }

  if (!isStringArray(data.technicalConsiderations)) {
    throw new Error("Invalid technicalConsiderations");
  }

  if (!data.budget || typeof data.budget !== "object") {
    throw new Error("Invalid budget");
  }

  const budget = data.budget as Record<string, unknown>;

  if (
    typeof budget.amount !== "number" ||
    !Number.isFinite(budget.amount) ||
    budget.amount <= 0
  ) {
    throw new Error("Invalid budget amount");
  }

  if (typeof budget.currency !== "string" || !budget.currency.trim()) {
    throw new Error("Invalid budget currency");
  }

  const validBudgetAssessments: BudgetAssessment[] = [
    "REASONABLE",
    "POSSIBLY_LOW",
    "POSSIBLY_HIGH",
    "UNKNOWN",
  ];

  if (
    !validBudgetAssessments.includes(
      data.budgetAssessment as BudgetAssessment,
    )
  ) {
    throw new Error("Invalid budgetAssessment");
  }

  if (
    typeof data.estimatedTimelineDays !== "number" ||
    !Number.isInteger(data.estimatedTimelineDays) ||
    data.estimatedTimelineDays <= 0
  ) {
    throw new Error("Invalid estimatedTimelineDays");
  }

  const validTimelineAssessments: TimelineAssessment[] = [
    "REASONABLE",
    "POSSIBLY_TOO_SHORT",
    "POSSIBLY_TOO_LONG",
    "UNKNOWN",
  ];

  if (
    !validTimelineAssessments.includes(
      data.timelineAssessment as TimelineAssessment,
    )
  ) {
    throw new Error("Invalid timelineAssessment");
  }

  const rawMilestones = validateMilestones(data.milestones);

  /**
   * Budget and timeline are authoritative from Project Assistant.
   * The primary model is not allowed to alter them.
   */
  if (
    budget.amount !== requirements.budget.amount ||
    normalise(budget.currency as string) !==
      normalise(requirements.budget.currency)
  ) {
    throw new Error(
      "Primary analysis changed the approved project budget",
    );
  }

  if (data.estimatedTimelineDays !== requirements.timeline.days) {
    throw new Error(
      "Primary analysis changed the approved project timeline",
    );
  }

  const projectBudget: ProjectBudget = {
    amount: budget.amount as number,
    currency: budget.currency as string,
  };

  return {
    projectTitle: data.projectTitle,
    projectDescription: data.projectDescription,
    projectType: data.projectType,
    platform: data.platform as string | null,
    targetUsers: data.targetUsers,
    coreFeatures: data.coreFeatures,
    complexity: data.complexity as ProjectComplexity,
    requiredSkills: data.requiredSkills,
    experienceLevel: data.experienceLevel as ExperienceLevel,
    keyDeliverables: data.keyDeliverables,
    technicalConsiderations: data.technicalConsiderations,
    budget: projectBudget,
    budgetAssessment: data.budgetAssessment as BudgetAssessment,
    estimatedTimelineDays: data.estimatedTimelineDays,
    timelineAssessment: data.timelineAssessment as TimelineAssessment,
    milestones: calculateMilestoneAmounts(rawMilestones, projectBudget),
  };
}

/* ============================================================
   PRIMARY MODEL ANALYSIS
   ============================================================ */

/**
 * ONE model creates the complete project analysis.
 *
 * This function is intentionally separate from verification.
 */
export async function analyzeProjectWithGonka(
  requirements: ProjectAssistantRequirements,
  model?: string,
): Promise<ProjectAnalysisModelResult> {
  const selectedModel =
    model ??
    process.env.GONKA_MODEL ??
    "deepseek-ai/DeepSeek-V4-Flash-0731";

  const prompt = buildProjectAnalysisPrompt(requirements);

  console.log(
    `Sending PRIMARY Project Analysis request to Gonka model: ${selectedModel}`,
  );

  const startTime = Date.now();

  const result = await gonka.chat.completions
    .create({
      model: selectedModel,
      messages: [
        {
          role: "system",
          content:
            "You are TrustHire's PRIMARY Project Analysis AI. Return only valid JSON.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0,
    })
    .withResponse();

  const response = result.data;
  const requestId = result.request_id;

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(
    `Received PRIMARY Project Analysis response from ${selectedModel} in ${elapsed}s`,
  );

  const content = response.choices[0]?.message?.content;

  if (!content) {
    throw new Error("Gonka returned an empty Project Analysis response");
  }

  let parsed: Record<string, unknown>;

  try {
    parsed = parseGonkaJson(content) as Record<string, unknown>;
  } catch {
    throw new Error(
      `Gonka returned invalid Project Analysis JSON: ${content}`,
    );
  }

  const analysis = validateAnalysis(parsed, requirements);

  const confidence = parsed.confidence;
  if (
    confidence !== "LOW" &&
    confidence !== "MEDIUM" &&
    confidence !== "HIGH"
  ) {
    throw new Error("Invalid Project Analysis confidence");
  }

  const reasoning = parsed.reasoning;
  if (typeof reasoning !== "string") {
    throw new Error("Invalid Project Analysis reasoning");
  }

  return {
    model: selectedModel,
    analysis,
    confidence,
    reasoning,
    requestId: requestId ?? "unknown",
  };
}

/* ============================================================
   VERIFIER PROMPT
   ============================================================ */

function buildVerificationPrompt(
  requirements: ProjectAssistantRequirements,
  analysis: ProjectAnalysis,
): string {
  return `
You are TrustHire's INDEPENDENT PROJECT ANALYSIS VERIFIER.

A PRIMARY AI model has already generated the project analysis below.

Your job is NOT to create a new project analysis.
Your job is ONLY to verify whether the PRIMARY AI's analysis is correct,
complete, internally consistent, and suitable for TrustHire.

You must independently judge the SAME primary analysis.

============================================================
CONFIRMED CLIENT REQUIREMENTS
============================================================

${JSON.stringify(requirements, null, 2)}

============================================================
PRIMARY AI ANALYSIS TO VERIFY
============================================================

${JSON.stringify(analysis, null, 2)}

============================================================
VERIFICATION RULES
============================================================

Check ALL of the following:

1. REQUIREMENTS ALIGNMENT
   - Does the analysis accurately reflect the confirmed client requirements?
   - No invented requirements.
   - No missing important confirmed requirements.

2. STRUCTURE VALIDITY
   - Project type, platform, complexity, skills, deliverables and
     technical considerations make sense for the confirmed requirements.

3. MILESTONE VALIDITY
   - There are between 2 and 6 milestones.
   - Milestones represent actual development work.
   - Milestones are logically ordered.
   - Each milestone has a clear purpose.

4. MILESTONE UNIQUENESS
   - No duplicate milestones.
   - Two milestones must NOT represent the same development phase.
   - For example, "Design & Architecture" and another "Design & Architecture"
     should be considered a FAIL unless they clearly represent different work.

5. ALLOCATION VALIDITY
   - Every percentage is an integer from 1 to 100.
   - Percentages sum to exactly 100.
   - Allocation is reasonably proportional to the work.

6. SEMANTIC DUPLICATE CHECK
   - Do NOT mark milestones as duplicates merely because they belong to the
     same broad category or development stage.
   - Mark them as duplicates only when they substantially represent the same
     work, objective, or deliverable.
   - For example, "Authentication & User Management" and
     "Payment Gateway Integration" are NOT duplicates.
   - "Design & Architecture" and "UI/UX Design" may be separate only if the
     descriptions clearly show distinct scopes.
   - Two milestones with essentially the same title and same purpose are a
     duplicate and should FAIL.

7. BUDGET AND TIMELINE
   - The analysis must preserve the exact approved budget.
   - The analysis must preserve the exact approved timeline.
   - It may assess them, but must not silently change them.

8. COMPLETENESS
   - The final structure is sufficient for TrustHire to publish the project
     and match freelancers.

============================================================
IMPORTANT
============================================================

Do NOT propose a replacement project structure.
Do NOT rewrite the milestones.
Do NOT generate a second analysis.

Only report whether the PRIMARY analysis passes verification and identify
specific issues if it fails.

Return ONLY valid JSON.

{
  "status": "PASS",
  "confidence": "HIGH",
  "issues": [],
  "checks": {
    "requirementsAlignment": true,
    "structureValidity": true,
    "milestoneValidity": true,
    "milestoneUniqueness": true,
    "allocationValidity": true,
    "budgetTimelinePreserved": true,
    "completeness": true
  },
  "reasoning": "Brief explanation of why the primary analysis passes or fails."
}
`.trim();
}

/* ============================================================
   SINGLE MODEL VERIFICATION
   ============================================================ */

export async function verifyProjectAnalysisWithGonka(
  requirements: ProjectAssistantRequirements,
  analysis: ProjectAnalysis,
  model: string,
): Promise<ProjectAnalysisVerificationResult> {
  const prompt = buildVerificationPrompt(requirements, analysis);

  console.log(
    `Sending Project Analysis VERIFICATION request to Gonka model: ${model}`,
  );

  const startTime = Date.now();

  const result = await gonka.chat.completions
    .create({
      model,
      messages: [
        {
          role: "system",
          content:
            "You are TrustHire's independent Project Analysis Verifier. Return only valid JSON.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0,
    })
    .withResponse();

  const response = result.data;
  const requestId = result.request_id;

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(
    `Received Project Analysis verification from ${model} in ${elapsed}s`,
  );

  const content = response.choices[0]?.message?.content;

  if (!content) {
    throw new Error(
      `Gonka returned an empty verification response from ${model}`,
    );
  }

  let parsed: Record<string, unknown>;

  try {
    parsed = parseGonkaJson(content) as Record<string, unknown>;
  } catch {
    throw new Error(
      `Gonka returned invalid verification JSON from ${model}: ${content}`,
    );
  }

  const status = parsed.status;
  if (status !== "PASS" && status !== "FAIL") {
    throw new Error(`Invalid verification status from ${model}`);
  }

  const confidence = parsed.confidence;
  if (
    confidence !== "LOW" &&
    confidence !== "MEDIUM" &&
    confidence !== "HIGH"
  ) {
    throw new Error(`Invalid verification confidence from ${model}`);
  }

  const issues = parsed.issues;
  if (!isStringArray(issues)) {
    throw new Error(`Invalid verification issues from ${model}`);
  }

  if (!parsed.checks || typeof parsed.checks !== "object") {
    throw new Error(`Invalid verification checks from ${model}`);
  }

  const checks = parsed.checks as Record<string, unknown>;

  const checkNames = [
    "requirementsAlignment",
    "structureValidity",
    "milestoneValidity",
    "milestoneUniqueness",
    "allocationValidity",
    "budgetTimelinePreserved",
    "completeness",
  ] as const;

  for (const checkName of checkNames) {
    if (typeof checks[checkName] !== "boolean") {
      throw new Error(
        `Invalid verification check '${checkName}' from ${model}`,
      );
    }
  }

  const reasoning = parsed.reasoning;
  if (typeof reasoning !== "string") {
    throw new Error(`Invalid verification reasoning from ${model}`);
  }

  return {
    model,
    status,
    confidence,
    issues,
    checks: {
      requirementsAlignment: checks.requirementsAlignment as boolean,
      structureValidity: checks.structureValidity as boolean,
      milestoneValidity: checks.milestoneValidity as boolean,
      milestoneUniqueness: checks.milestoneUniqueness as boolean,
      allocationValidity: checks.allocationValidity as boolean,
      budgetTimelinePreserved: checks.budgetTimelinePreserved as boolean,
      completeness: checks.completeness as boolean,
    },
    reasoning,
    requestId: requestId ?? "unknown",
  };
}

/* ============================================================
   VERIFICATION CONSENSUS
   ============================================================ */

/**
 * All verifier models judge the SAME primary analysis.
 *
 * A PASS requires a strict majority of successful verifiers.
 * With two verifiers, both must PASS.
 */
function calculateVerificationConsensus(
  verifierResults: ProjectAnalysisVerificationResult[],
): ProjectAnalysisVerification {
  if (verifierResults.length === 0) {
    throw new Error("No successful Project Analysis verifiers");
  }

  const passedCount = verifierResults.filter(
    (result) => result.status === "PASS",
  ).length;

  const failedCount = verifierResults.length - passedCount;

  /**
   * Strict majority:
   * 1 verifier  -> 1/1
   * 2 verifiers -> 2/2
   * 3 verifiers -> 2/3
   * 4 verifiers -> 3/4
   */
  const requiredPasses = Math.floor(verifierResults.length / 2) + 1;

  const passed = passedCount >= requiredPasses;

  let resolutionMethod: VerificationResolutionMethod;

  if (passedCount === verifierResults.length) {
    resolutionMethod = "CONSENSUS";
  } else if (passed) {
    resolutionMethod = "MAJORITY";
  } else {
    resolutionMethod = "REJECTED";
  }

  const confidence: "LOW" | "MEDIUM" | "HIGH" =
    passedCount === verifierResults.length
      ? "HIGH"
      : passed
        ? "MEDIUM"
        : "LOW";

  const allIssues = verifierResults.flatMap((result) =>
    result.issues.map((issue) => `[${result.model}] ${issue}`),
  );

  const reasoning = passed
    ? `${passedCount}/${verifierResults.length} independent verifier(s) passed the same primary analysis.`
    : `${passedCount}/${verifierResults.length} independent verifier(s) passed. The primary analysis was rejected. ${
        allIssues.length > 0
          ? `Issues: ${allIssues.join(" | ")}`
          : "One or more verifiers found the analysis unsuitable."
      }`;

  return {
    status: passed ? "PASS" : "FAIL",
    passedCount,
    failedCount,
    totalModels: verifierResults.length,
    confidence,
    resolutionMethod,
    verifierResults,
    reasoning,
  };
}

/* ============================================================
   MODEL SELECTION
   ============================================================ */

function getPrimaryModel(): string {
  // TrustHire's primary model is MiniMax.
  return (
    process.env.GONKA_MODEL?.trim() ||
    "MiniMaxAI/MiniMax-M2.7"
  );
}

function getVerifierModels(_primaryModel: string): string[] {
  /**
   * TrustHire verification uses TWO independent verification calls:
   *
   * 1. MiniMax
   * 2. DeepSeek
   *
   * MiniMax is intentionally allowed to verify the analysis even though
   * MiniMax is also the primary analysis model. The verifier uses a
   * different prompt and receives the already-generated primary analysis;
   * it does NOT generate a replacement analysis.
   *
   * You can override these defaults with:
   *
   * GONKA_VERIFIER_MODELS=MiniMaxAI/MiniMax-M2.7,deepseek-ai/DeepSeek-V4-Flash-0731
   */
  const configuredVerifiers = process.env.GONKA_VERIFIER_MODELS
    ?.split(",")
    .map((model) => model.trim())
    .filter(Boolean);

  const candidates =
    configuredVerifiers && configuredVerifiers.length > 0
      ? configuredVerifiers
      : [
          "MiniMaxAI/MiniMax-M2.7",
          "deepseek-ai/DeepSeek-V4-Flash-0731",
        ];

  const unique = [...new Set(candidates.map((model) => model.trim()))];

  if (unique.length === 0) {
    throw new Error(
      "No Project Analysis verifier models configured.",
    );
  }

  return unique;
}

/* ============================================================
   MAIN PROJECT ANALYSIS ENTRY POINT
   ============================================================ */

/**
 * TrustHire Project Analysis pipeline:
 *
 * STEP 1:
 * One PRIMARY model generates the complete project structure.
 *
 * STEP 2:
 * MiniMax and DeepSeek independently receive that exact same structure
 * and judge it. They do NOT generate alternative structures.
 *
 * STEP 3:
 * MiniMax and DeepSeek vote PASS/FAIL.
 *
 * With the default two-verifier setup, BOTH must PASS for approval.
 *
 * STEP 4:
 * The primary analysis is returned unchanged. It should only be published
 * / used for escrow when verification.status === "PASS".
 */
export async function analyzeProject(
  requirements: ProjectAssistantRequirements,
): Promise<ProjectAnalysisResult> {
  if (!requirements || typeof requirements !== "object") {
    throw new Error("Project Assistant requirements are required");
  }

  if (!requirements.projectTitle?.trim()) {
    throw new Error("Project title is required");
  }

  if (!requirements.description?.trim()) {
    throw new Error("Project description is required");
  }

  if (!Array.isArray(requirements.coreFeatures)) {
    throw new Error("Project core features are required");
  }

  if (
    !requirements.budget ||
    typeof requirements.budget.amount !== "number" ||
    !Number.isFinite(requirements.budget.amount) ||
    requirements.budget.amount <= 0
  ) {
    throw new Error("Approved project budget is required");
  }

  if (
    !requirements.timeline ||
    typeof requirements.timeline.days !== "number" ||
    !Number.isInteger(requirements.timeline.days) ||
    requirements.timeline.days <= 0
  ) {
    throw new Error("Approved project timeline is required");
  }

  /* ----------------------------------------------------------
     STEP 1: ONE PRIMARY MODEL CREATES THE STRUCTURE
     ---------------------------------------------------------- */

  const primaryModel = getPrimaryModel();

  console.log(
    `Running ONE PRIMARY Project Analysis model: ${primaryModel}`,
  );

  const primaryResult = await analyzeProjectWithGonka(
    requirements,
    primaryModel,
  );

  console.log(
    `Primary analysis created. Starting independent multi-model verification...`,
  );

  /* ----------------------------------------------------------
     STEP 2: MULTIPLE MODELS VERIFY THE SAME STRUCTURE
     ---------------------------------------------------------- */

  const verifierModels = getVerifierModels(primaryModel);

  console.log(
    `Running ${verifierModels.length} independent Project Analysis verifier(s) in parallel...`,
  );

  const execution = await runAcrossModels(verifierModels, (model) =>
    verifyProjectAnalysisWithGonka(
      requirements,
      primaryResult.analysis,
      model,
    ),
  );

  const successfulVerifications = execution.results.filter(
    (
      result,
    ): result is typeof result & {
      success: true;
      result: ProjectAnalysisVerificationResult;
    } => result.success && result.result !== undefined,
  );

  const failedVerificationCalls = execution.results.filter(
    (result) => !result.success,
  ).length;

  if (successfulVerifications.length === 0) {
    throw new Error(
      "All Project Analysis verifier models failed to return a valid verification.",
    );
  }

  const verifierResults = successfulVerifications.map(
    (result) => result.result,
  );

  const verification = calculateVerificationConsensus(verifierResults);

  console.log(
    `Project Analysis verification result: ${verification.status} (${verification.passedCount}/${verification.totalModels} passed)`,
  );

  if (verification.status === "FAIL") {
    console.warn(
      `Primary Project Analysis REJECTED by multi-model verification.`,
    );
    console.warn(
      `Verifier issues: ${verification.verifierResults
        .flatMap((result) =>
          result.issues.map((issue) => `[${result.model}] ${issue}`),
        )
        .join(" | ")}`,
    );
  } else {
    console.log(
      `Primary Project Analysis APPROVED by multi-model verification.`,
    );
  }

  /* ----------------------------------------------------------
     STEP 3: RETURN PRIMARY ANALYSIS + VERIFICATION
     ---------------------------------------------------------- */

return {
  analysis: primaryResult.analysis,
  verification,

  primaryRequestId: primaryResult.requestId,

  verifierRequestIds: verifierResults.map((result) => ({
    model: result.model,
    requestId: result.requestId,
  })),

  successfulModels: 1,
  failedModels: failedVerificationCalls,
};
}
