import { gonka } from "../client";
import { parseGonkaJson } from "../responseParser";
import { runAcrossModels } from "../multiModel";
import { GONKA_MODELS } from "../models";

/* ============================================================
   TYPES
   ============================================================ */

export type ExperienceLevel =
  | "Beginner"
  | "Intermediate"
  | "Expert";

export type ProjectComplexity =
  | "Simple"
  | "Moderate"
  | "Complex"
  | "Highly Complex";

export type BudgetAssessment =
  | "REASONABLE"
  | "POSSIBLY_LOW"
  | "POSSIBLY_HIGH"
  | "UNKNOWN";

export type TimelineAssessment =
  | "REASONABLE"
  | "POSSIBLY_TOO_SHORT"
  | "POSSIBLY_TOO_LONG"
  | "UNKNOWN";

export type AnalysisResolutionMethod =
  | "CONSENSUS"
  | "MAJORITY"
  | "RESOLVED"
  | "UNRESOLVED";

export interface ProjectBudget {
  amount: number;
  currency: string;
}

export interface ProjectTimeline {
  days: number;
}

/**
 * Confirmed information produced by projectAssistant.ts.
 *
 * ProjectAnalysis must analyse this information rather than
 * re-interviewing the client.
 */
export interface ProjectAssistantRequirements {
  projectTitle: string;
  description: string;
  coreFeatures: string[];
  targetUsers?: string[];
  platform?: string;
  budget: ProjectBudget;
  timeline: ProjectTimeline;
}

/* ============================================================
   MILESTONES
   ============================================================ */

/**
 * Milestone generated by Project Analysis.
 *
 * percentageAllocation is generated by AI.
 * amount is calculated by TrustHire from the approved budget.
 */
export interface ProjectMilestone {
  title: string;
  description: string;
  percentageAllocation: number;
  amount: number;
}

/* ============================================================
   PROJECT ANALYSIS
   ============================================================ */

export interface ProjectAnalysis {
  projectTitle: string;
  projectDescription: string;
  projectType: string;
  platform: string | null;
  targetUsers: string[];
  coreFeatures: string[];
  complexity: ProjectComplexity;
  requiredSkills: string[];
  experienceLevel: ExperienceLevel;
  keyDeliverables: string[];
  technicalConsiderations: string[];
  budget: ProjectBudget;
  budgetAssessment: BudgetAssessment;
  estimatedTimelineDays: number;
  timelineAssessment: TimelineAssessment;
  milestones: ProjectMilestone[];
}

/* ============================================================
   CONFLICT & RESOLUTION TYPES
   ============================================================ */

export interface ProjectAnalysisConflict {
  field: string;
  values: { model: string; value: unknown }[];
  resolution: unknown;
  reason?: string;
}

/* ============================================================
   MODEL RESULT TYPES
   ============================================================ */

export interface ProjectAnalysisModelResult {
  model: string;
  analysis: ProjectAnalysis;
  confidence: "LOW" | "MEDIUM" | "HIGH";
  reasoning: string;
  requestId: string;
}

export interface ProjectAnalysisConsensus {
  analysis: ProjectAnalysis;
  agreementCount: number;
  totalModels: number;
  confidence: "LOW" | "MEDIUM" | "HIGH";
  hasConflict: boolean;
  conflicts: ProjectAnalysisConflict[];
  resolutionMethod: AnalysisResolutionMethod;
  reasoning: string;
}

export interface ProjectAnalysisResult {
  analysis: ProjectAnalysis;
  consensus: ProjectAnalysisConsensus;
  modelResults: ProjectAnalysisModelResult[];
  successfulModels: number;
  failedModels: number;
}

/* ============================================================
   PROMPT
   ============================================================ */

function buildProjectAnalysisPrompt(
  requirements: ProjectAssistantRequirements,
): string {
  return `
You are TrustHire's Project Analysis AI.

The Project Assistant has already spoken with the client and confirmed the client's requirements.

Your job is to analyse those confirmed requirements and create a structured project specification for TrustHire and potential freelancers.

You are NOT the Project Assistant.
Do not continue the conversation with the client.
Do not ask questions.
Do not change the client's approved budget or timeline.
Do not invent client requirements.

============================================================
CONFIRMED CLIENT REQUIREMENTS
============================================================

${JSON.stringify(requirements, null, 2)}

============================================================
YOUR RESPONSIBILITY
============================================================

Analyse the confirmed project and determine:
1. Project type
2. Freelancer-facing project description
3. Platform
4. Target users
5. Core features
6. Project complexity ("Simple" | "Moderate" | "Complex" | "Highly Complex")
7. Required skills (Technical skills for freelancer matching)
8. Recommended experience level ("Beginner" | "Senior" | "Expert")
9. Key deliverables
10. Technical considerations
11. Budget assessment ("REASONABLE" | "POSSIBLY_LOW" | "POSSIBLY_HIGH" | "UNKNOWN")
12. Timeline assessment ("REASONABLE" | "POSSIBLY_TOO_SHORT" | "POSSIBLY_TOO_LONG" | "UNKNOWN")
13. Project milestones (2 to 6 milestones with percentage allocations summing to 100)

============================================================
MILESTONE REQUIREMENTS
============================================================

Create a practical milestone breakdown for the project:
- Create between 2 and 6 milestones (prefer 3 to 5).
- Milestones must represent distinct development phases (e.g. Design/Spec, Core Implementation, Integration/Features, Testing/QA/Deployment).
- Each milestone must have a clear title, description, and integer percentageAllocation.
- The percentage allocations MUST sum to exactly 100.
- Do NOT calculate money amounts (TrustHire will compute exact amounts from the approved budget).

============================================================
OUTPUT FORMAT
============================================================

Return ONLY valid JSON.
Do NOT use markdown code fences.
Do NOT include <think> tags.

Use exactly this JSON structure:

{
  "projectTitle": "${requirements.projectTitle}",
  "projectDescription": "Professional freelancer-facing description",
  "projectType": "e.g. Web Application / E-commerce",
  "platform": "e.g. Web / Mobile / Full-Stack",
  "targetUsers": ["string"],
  "coreFeatures": ["string"],
  "complexity": "Moderate",
  "requiredSkills": ["TypeScript", "React", "Node.js"],
  "experienceLevel": "Intermediate",
  "keyDeliverables": ["string"],
  "technicalConsiderations": ["string"],
  "budget": {
    "amount": ${requirements.budget.amount},
    "currency": "${requirements.budget.currency}"
  },
  "budgetAssessment": "REASONABLE",
  "estimatedTimelineDays": ${requirements.timeline.days},
  "timelineAssessment": "REASONABLE",
  "milestones": [
    {
      "title": "Design & Architecture",
      "description": "System architecture, UI wireframes, and project setup.",
      "percentageAllocation": 25
    },
    {
      "title": "Core Implementation",
      "description": "Implement primary features and business logic.",
      "percentageAllocation": 45
    },
    {
      "title": "Testing, QA & Deployment",
      "description": "End-to-end testing, bug fixes, and deployment.",
      "percentageAllocation": 30
    }
  ],
  "confidence": "HIGH",
  "reasoning": "Brief explanation of the analysis."
}
`.trim();
}

/* ============================================================
   VALIDATION HELPERS
   ============================================================ */

function isStringArray(value: unknown): value is string[] {
  return (
    Array.isArray(value) &&
    value.every((item) => typeof item === "string")
  );
}

function isValidPercentage(value: unknown): value is number {
  return (
    typeof value === "number" &&
    Number.isFinite(value) &&
    Number.isInteger(value) &&
    value >= 1 &&
    value <= 100
  );
}

/* ============================================================
   MILESTONE VALIDATION & AMOUNT CALCULATION
   ============================================================ */

interface RawMilestone {
  title: string;
  description: string;
  percentageAllocation: number;
}

function validateMilestones(value: unknown): RawMilestone[] {
  if (!Array.isArray(value)) {
    throw new Error("Invalid milestones format");
  }

  if (value.length < 2 || value.length > 6) {
    throw new Error("Milestones must contain between 2 and 6 items");
  }

  const milestones = value.map((item, index) => {
    if (!item || typeof item !== "object") {
      throw new Error(`Invalid milestone at index ${index}`);
    }

    const data = item as Record<string, unknown>;

    if (typeof data.title !== "string" || !data.title.trim()) {
      throw new Error(`Invalid milestone title at index ${index}`);
    }

    if (typeof data.description !== "string" || !data.description.trim()) {
      throw new Error(`Invalid milestone description at index ${index}`);
    }

    if (!isValidPercentage(data.percentageAllocation)) {
      throw new Error(`Invalid milestone percentage at index ${index}`);
    }

    return {
      title: data.title.trim(),
      description: data.description.trim(),
      percentageAllocation: data.percentageAllocation,
    };
  });

  const total = milestones.reduce(
    (sum, m) => sum + m.percentageAllocation,
    0,
  );

  if (total !== 100) {
    throw new Error(
      `Milestone percentages must total exactly 100. Received ${total}`,
    );
  }

  return milestones;
}

/**
 * Converts AI-generated percentages into exact currency amounts.
 * Uses the Largest Remainder Method (Hare-Niemeyer) to prevent rounding loss.
 */
export function calculateMilestoneAmounts(
  milestones: RawMilestone[],
  budget: ProjectBudget,
): ProjectMilestone[] {
  const totalCents = Math.round(budget.amount * 100);

  const exactAmounts = milestones.map(
    (m) => (totalCents * m.percentageAllocation) / 100,
  );

  const amounts = exactAmounts.map((amount) => Math.floor(amount));

  let remaining =
    totalCents - amounts.reduce((sum, amount) => sum + amount, 0);

  const remainderOrder = exactAmounts
    .map((exact, index) => ({
      index,
      fraction: exact - amounts[index],
    }))
    .sort((a, b) => b.fraction - a.fraction);

  for (const item of remainderOrder) {
    if (remaining <= 0) break;
    amounts[item.index] += 1;
    remaining -= 1;
  }

  return milestones.map((m, index) => ({
    title: m.title,
    description: m.description,
    percentageAllocation: m.percentageAllocation,
    amount: amounts[index] / 100,
  }));
}

/* ============================================================
   ANALYSIS VALIDATION
   ============================================================ */

function validateAnalysis(value: unknown): ProjectAnalysis {
  if (!value || typeof value !== "object") {
    throw new Error("Project analysis is not an object");
  }

  const data = value as Record<string, unknown>;

  if (typeof data.projectTitle !== "string") {
    throw new Error("Invalid projectTitle");
  }

  if (typeof data.projectDescription !== "string") {
    throw new Error("Invalid projectDescription");
  }

  if (typeof data.projectType !== "string") {
    throw new Error("Invalid projectType");
  }

  if (data.platform !== null && typeof data.platform !== "string") {
    throw new Error("Invalid platform");
  }

  if (!isStringArray(data.targetUsers)) {
    throw new Error("Invalid targetUsers");
  }

  if (!isStringArray(data.coreFeatures)) {
    throw new Error("Invalid coreFeatures");
  }

  const validComplexities: ProjectComplexity[] = [
    "Simple",
    "Moderate",
    "Complex",
    "Highly Complex",
  ];

  if (!validComplexities.includes(data.complexity as ProjectComplexity)) {
    throw new Error("Invalid complexity");
  }

  if (!isStringArray(data.requiredSkills)) {
    throw new Error("Invalid requiredSkills");
  }

  const validExperienceLevels: ExperienceLevel[] = [
    "Beginner",
    "Intermediate",
    "Expert",
  ];

  if (
    !validExperienceLevels.includes(data.experienceLevel as ExperienceLevel)
  ) {
    throw new Error("Invalid experienceLevel");
  }

  if (!isStringArray(data.keyDeliverables)) {
    throw new Error("Invalid keyDeliverables");
  }

  if (!isStringArray(data.technicalConsiderations)) {
    throw new Error("Invalid technicalConsiderations");
  }

  if (!data.budget || typeof data.budget !== "object") {
    throw new Error("Invalid budget");
  }

  const budget = data.budget as Record<string, unknown>;

  if (
    typeof budget.amount !== "number" ||
    !Number.isFinite(budget.amount) ||
    budget.amount <= 0
  ) {
    throw new Error("Invalid budget amount");
  }

  if (typeof budget.currency !== "string" || !budget.currency.trim()) {
    throw new Error("Invalid budget currency");
  }

  const validBudgetAssessments: BudgetAssessment[] = [
    "REASONABLE",
    "POSSIBLY_LOW",
    "POSSIBLY_HIGH",
    "UNKNOWN",
  ];

  if (
    !validBudgetAssessments.includes(
      data.budgetAssessment as BudgetAssessment,
    )
  ) {
    throw new Error("Invalid budgetAssessment");
  }

  if (
    typeof data.estimatedTimelineDays !== "number" ||
    !Number.isInteger(data.estimatedTimelineDays) ||
    data.estimatedTimelineDays <= 0
  ) {
    throw new Error("Invalid estimatedTimelineDays");
  }

  const validTimelineAssessments: TimelineAssessment[] = [
    "REASONABLE",
    "POSSIBLY_TOO_SHORT",
    "POSSIBLY_TOO_LONG",
    "UNKNOWN",
  ];

  if (
    !validTimelineAssessments.includes(
      data.timelineAssessment as TimelineAssessment,
    )
  ) {
    throw new Error("Invalid timelineAssessment");
  }

  const rawMilestones = validateMilestones(data.milestones);

  const projectBudget: ProjectBudget = {
    amount: budget.amount as number,
    currency: budget.currency as string,
  };

  return {
    projectTitle: data.projectTitle,
    projectDescription: data.projectDescription,
    projectType: data.projectType,
    platform: data.platform as string | null,
    targetUsers: data.targetUsers,
    coreFeatures: data.coreFeatures,
    complexity: data.complexity as ProjectComplexity,
    requiredSkills: data.requiredSkills,
    experienceLevel: data.experienceLevel as ExperienceLevel,
    keyDeliverables: data.keyDeliverables,
    technicalConsiderations: data.technicalConsiderations,
    budget: projectBudget,
    budgetAssessment: data.budgetAssessment as BudgetAssessment,
    estimatedTimelineDays: data.estimatedTimelineDays,
    timelineAssessment: data.timelineAssessment as TimelineAssessment,
    milestones: calculateMilestoneAmounts(rawMilestones, projectBudget),
  };
}

/* ============================================================
   SINGLE MODEL ANALYSIS
   ============================================================ */

export async function analyzeProjectWithGonka(
  requirements: ProjectAssistantRequirements,
  model?: string,
): Promise<ProjectAnalysisModelResult> {
  const selectedModel = model ?? process.env.GONKA_MODEL ?? "deepseek-ai/DeepSeek-V4-Flash-0731";

  const prompt = buildProjectAnalysisPrompt(requirements);

  console.log(`Sending Project Analysis request to Gonka model: ${selectedModel}`);

  const startTime = Date.now();

  const response = await gonka.chat.completions.create({
    model: selectedModel,
    messages: [
      {
        role: "system",
        content: "You are TrustHire's Project Analysis AI. Return only valid JSON.",
      },
      {
        role: "user",
        content: prompt,
      },
    ],
    temperature: 0,
  });

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`Received Project Analysis response from ${selectedModel} in ${elapsed}s`);

  const content = response.choices[0]?.message?.content;

  if (!content) {
    throw new Error("Gonka returned an empty Project Analysis response");
  }

  let parsed: Record<string, unknown>;

  try {
    parsed = parseGonkaJson(content) as Record<string, unknown>;
  } catch {
    throw new Error(`Gonka returned invalid Project Analysis JSON: ${content}`);
  }

  const analysis = validateAnalysis(parsed);

  const confidence = parsed.confidence;
  if (confidence !== "LOW" && confidence !== "MEDIUM" && confidence !== "HIGH") {
    throw new Error("Invalid Project Analysis confidence");
  }

  const reasoning = parsed.reasoning;
  if (typeof reasoning !== "string") {
    throw new Error("Invalid Project Analysis reasoning");
  }

  return {
    model: selectedModel,
    analysis,
    confidence,
    reasoning,
    requestId: response.id ?? "unknown",
  };
}

/* ============================================================
   CONSENSUS & RESOLUTION HELPERS
   ============================================================ */

function normalise(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/\s+/g, " ");
}

/**
 * Maps common model-specific wording to canonical concepts.
 * This is intentionally conservative so freelancer matching does not
 * accidentally require every alternative technology mentioned by a model.
 */
function canonicalSkill(value: string): string {
  const text = normalise(value);

  if (/\bhtml\b.*\bcss\b|html5\/css3|html\/css/.test(text)) {
    return "HTML5/CSS3";
  }
  if (/\bjavascript\b|\btypescript\b/.test(text)) {
    return text.includes("typescript") ? "TypeScript" : "JavaScript";
  }
  if (/react/.test(text)) return "React";
  if (/vue/.test(text)) return "Vue.js";
  if (/node\.?js/.test(text)) return "Node.js";
  if (/\bphp\b/.test(text)) return "PHP";
  if (/mysql|postgres|postgresql|sql database|database management/.test(text)) {
    return "SQL Database";
  }
  if (/payment.*(gateway|integration)|stripe|paypal|fpX|payment processing/.test(text)) {
    return "Payment Gateway Integration";
  }
  if (/responsive.*(web|design)|mobile-first|responsive design/.test(text)) {
    return "Responsive Web Design";
  }
  if (/ui\/?ux|user interface|user experience/.test(text)) return "UI/UX Design";
  if (/seo/.test(text)) return "Basic SEO";
  if (/backend|back-end|server-side/.test(text)) return "Backend Development";
  if (/frontend|front-end|client-side/.test(text)) return "Frontend Development";
  if (/web security|security|pci dss/.test(text)) return "Web Security";
  if (/e-commerce|ecommerce/.test(text)) return "E-commerce Development";

  return value.trim();
}

function canonicalFeature(value: string): string {
  const text = normalise(value);

  if (/product (showcase|catalog|catalogue)|showcase.*product/.test(text)) {
    if (/search|filter|categor/.test(text)) return "Product catalog, search and filtering";
    return "Product showcase";
  }
  if (/product.*(information|detail).*pricing|pricing.*product/.test(text)) {
    return "Product information and pricing";
  }
  if (/shopping cart|add.*cart|cart functionality/.test(text)) return "Shopping cart";
  if (/online ordering|place orders|order processing/.test(text)) return "Online ordering";
  if (/online payment|payment processing|payment gateway/.test(text)) return "Online payment";
  if (/order confirmation|order management/.test(text)) return "Order management";

  return value.trim();
}

function canonicalDeliverable(value: string): string {
  const text = normalise(value);
  if (/product (catalog|catalogue)|product management/.test(text)) return "Product catalogue and management";
  if (/shopping cart/.test(text)) return "Shopping cart and checkout";
  if (/payment/.test(text)) return "Online payment integration";
  if (/order/.test(text)) return "Order processing and management";
  if (/responsive/.test(text)) return "Responsive web design";
  if (/deploy/.test(text)) return "Deployment and setup";
  if (/documentation|user manual|source code/.test(text)) return "Documentation and source code";
  return value.trim();
}

function canonicalTechnicalConsideration(value: string): string {
  const text = normalise(value);
  if (/payment|pci|ssl|https/.test(text)) return "Secure payment processing and HTTPS";
  if (/database|scalable product database/.test(text)) return "Database design for products, orders and customer data";
  if (/shopping cart|state management/.test(text)) return "Shopping cart state management";
  if (/form validation|checkout/.test(text)) return "Checkout validation";
  if (/responsive|mobile-first/.test(text)) return "Mobile-responsive design";
  if (/seo/.test(text)) return "Basic SEO optimization";
  if (/scalab/.test(text)) return "Future scalability";
  if (/local payment|fpx/.test(text)) return "Local payment gateway integration";
  return value.trim();
}

function calculateOverlap(a: string[], b: string[], canonicalizer?: (value: string) => string): number {
  if (a.length === 0 || b.length === 0) return 0;

  const map = canonicalizer ?? ((value: string) => value);
  const aSet = new Set(a.map((item) => normalise(map(item))));
  const bSet = new Set(b.map((item) => normalise(map(item))));
  const intersection = [...aSet].filter((item) => bSet.has(item)).length;
  const union = new Set([...aSet, ...bSet]).size;

  return union === 0 ? 0 : intersection / union;
}

function chooseMajorityString(values: string[]): string {
  if (values.length === 0) return "";
  const counts = new Map<string, { value: string; count: number }>();

  for (const value of values) {
    const key = normalise(value);
    const existing = counts.get(key);
    if (existing) {
      existing.count++;
    } else {
      counts.set(key, { value, count: 1 });
    }
  }

  return [...counts.values()].sort((a, b) => b.count - a.count)[0].value;
}

function chooseComplexity(values: ProjectComplexity[]): ProjectComplexity {
  const complexityRank: Record<ProjectComplexity, number> = {
    Simple: 1,
    Moderate: 2,
    Complex: 3,
    "Highly Complex": 4,
  };

  const counts = new Map<ProjectComplexity, number>();
  for (const value of values) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  const sorted = [...counts.entries()].sort((a, b) => {
    if (b[1] !== a[1]) return b[1] - a[1];
    // In case of tie, choose the more realistic/conservative higher complexity
    return complexityRank[b[0]] - complexityRank[a[0]];
  });

  return sorted[0][0];
}

function chooseExperienceLevel(values: ExperienceLevel[]): ExperienceLevel {
  const levelRank: Record<ExperienceLevel, number> = {
    Beginner: 1,
    Intermediate: 2,
    Expert: 3,
  };

  const counts = new Map<ExperienceLevel, number>();
  for (const value of values) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  const sorted = [...counts.entries()].sort((a, b) => {
    if (b[1] !== a[1]) return b[1] - a[1];
    return levelRank[b[0]] - levelRank[a[0]];
  });

  return sorted[0][0];
}

function chooseBudget(values: ProjectBudget[]): ProjectBudget {
  const currency = chooseMajorityString(values.map((v) => v.currency));
  const matching = values
    .filter((v) => normalise(v.currency) === normalise(currency))
    .map((v) => v.amount)
    .sort((a, b) => a - b);

  return {
    amount: matching[Math.floor(matching.length / 2)],
    currency,
  };
}

function chooseTimeline(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

function mergeStringArrays(
  arrays: string[][],
  canonicalizer: (value: string) => string = (value) => value,
): string[] {
  const counts = new Map<string, { value: string; count: number }>();

  for (const array of arrays) {
    // A model should only contribute once to a canonical concept.
    const seenByModel = new Set<string>();

    for (const value of array) {
      const canonical = canonicalizer(value);
      const key = normalise(canonical);
      if (seenByModel.has(key)) continue;
      seenByModel.add(key);

      const existing = counts.get(key);
      if (existing) {
        existing.count++;
      } else {
        counts.set(key, { value: canonical, count: 1 });
      }
    }
  }

  const minimumAgreement = Math.max(1, Math.ceil(arrays.length / 2));

  return [...counts.values()]
    .filter((item) => item.count >= minimumAgreement)
    .sort((a, b) => b.count - a.count)
    .map((item) => item.value);
}

/* ============================================================
   SEMANTIC MILESTONE MERGING
   ============================================================ */

type MilestoneStage =
  | "PLANNING_DESIGN"
  | "CORE_DEVELOPMENT"
  | "INTEGRATION_FEATURES"
  | "TESTING_DEPLOYMENT";

function classifyMilestoneStage(title: string, description: string): MilestoneStage {
  const text = `${title} ${description}`.toLowerCase();

  if (
    text.includes("test") ||
    text.includes("qa") ||
    text.includes("deploy") ||
    text.includes("launch") ||
    text.includes("handover") ||
    text.includes("documentation")
  ) {
    return "TESTING_DEPLOYMENT";
  }

  if (
    text.includes("payment") ||
    text.includes("gateway") ||
    text.includes("auth") ||
    text.includes("integration") ||
    text.includes("admin") ||
    text.includes("notification") ||
    text.includes("smart contract") ||
    text.includes("escrow")
  ) {
    return "INTEGRATION_FEATURES";
  }

  if (
    text.includes("design") ||
    text.includes("architecture") ||
    text.includes("wireframe") ||
    text.includes("spec") ||
    text.includes("planning") ||
    text.includes("setup") ||
    text.includes("prototype")
  ) {
    return "PLANNING_DESIGN";
  }

  return "CORE_DEVELOPMENT";
}

/**
 * Merges milestones across models semantically by development phase/stage.
 * Avoids losing specific features and prevents duplicate work.
 */
function buildSemanticMilestoneConsensus(
  results: ProjectAnalysisModelResult[],
  budget: ProjectBudget,
): ProjectMilestone[] {
  const stageOrder: MilestoneStage[] = [
    "PLANNING_DESIGN",
    "CORE_DEVELOPMENT",
    "INTEGRATION_FEATURES",
    "TESTING_DEPLOYMENT",
  ];

  const stageBuckets = new Map<
    MilestoneStage,
    { title: string; description: string; percentage: number; count: number }[]
  >();

  for (const stage of stageOrder) {
    stageBuckets.set(stage, []);
  }

  for (const modelResult of results) {
    for (const milestone of modelResult.analysis.milestones) {
      const stage = classifyMilestoneStage(milestone.title, milestone.description);
      stageBuckets.get(stage)?.push({
        title: milestone.title,
        description: milestone.description,
        percentage: milestone.percentageAllocation,
        count: 1,
      });
    }
  }

  const mergedDrafts: RawMilestone[] = [];

  for (const stage of stageOrder) {
    const items = stageBuckets.get(stage) || [];
    if (items.length === 0) continue;

    // Pick most representative title
    const title = chooseMajorityString(items.map((i) => i.title));
    const description = chooseMajorityString(items.map((i) => i.description));

    // Calculate median percentage for this phase
    const sortedPercentages = items.map((i) => i.percentage).sort((a, b) => a - b);
    const medianPercentage =
      sortedPercentages[Math.floor(sortedPercentages.length / 2)];

    mergedDrafts.push({
      title,
      description,
      percentageAllocation: medianPercentage,
    });
  }

  // Fallback if semantic bucketing produced fewer than 2 milestones
  if (mergedDrafts.length < 2) {
    const bestSet = results[0].analysis.milestones;
    return calculateMilestoneAmounts(
      bestSet.map((m) => ({
        title: m.title,
        description: m.description,
        percentageAllocation: m.percentageAllocation,
      })),
      budget,
    );
  }

  // Normalize percentages so they sum to exactly 100%
  const normalized = mergedDrafts.map((m) => ({
    ...m,
    percentageAllocation: Math.max(1, Math.round(m.percentageAllocation)),
  }));

  let total = normalized.reduce((sum, m) => sum + m.percentageAllocation, 0);

  while (total > 100) {
    const maxItem = [...normalized]
      .filter((m) => m.percentageAllocation > 5)
      .sort((a, b) => b.percentageAllocation - a.percentageAllocation)[0];

    if (!maxItem) break;
    maxItem.percentageAllocation--;
    total--;
  }

  while (total < 100) {
    const minItem = [...normalized].sort(
      (a, b) => a.percentageAllocation - b.percentageAllocation,
    )[0];

    if (!minItem) break;
    minItem.percentageAllocation++;
    total++;
  }

  return calculateMilestoneAmounts(normalized, budget);
}

/* ============================================================
   CONFLICT DETECTION & RESOLUTION
   ============================================================ */

function detectConflicts(
  results: ProjectAnalysisModelResult[],
  consensus: ProjectAnalysis,
): ProjectAnalysisConflict[] {
  const conflicts: ProjectAnalysisConflict[] = [];

  if (results.length < 2) return conflicts;

  const recordScalarConflict = (
    field: string,
    values: unknown[],
    resolution: unknown,
  ) => {
    const unique = new Set(values.map((value) => normalise(String(value))));
    if (unique.size > 1) {
      conflicts.push({
        field,
        values: results.map((r, index) => ({ model: r.model, value: values[index] })),
        resolution,
        reason: `Models disagreed on ${field}. Final value was resolved from the model results.`,
      });
    }
  };

  recordScalarConflict(
    "complexity",
    results.map((r) => r.analysis.complexity),
    consensus.complexity,
  );

  recordScalarConflict(
    "experienceLevel",
    results.map((r) => r.analysis.experienceLevel),
    consensus.experienceLevel,
  );

  recordScalarConflict(
    "budgetAssessment",
    results.map((r) => r.analysis.budgetAssessment),
    consensus.budgetAssessment,
  );

  recordScalarConflict(
    "timelineAssessment",
    results.map((r) => r.analysis.timelineAssessment),
    consensus.timelineAssessment,
  );

  const arrayChecks: Array<{
    field: string;
    selector: (analysis: ProjectAnalysis) => string[];
    canonicalizer: (value: string) => string;
    resolution: string[];
  }> = [
    {
      field: "requiredSkills",
      selector: (a) => a.requiredSkills,
      canonicalizer: canonicalSkill,
      resolution: consensus.requiredSkills,
    },
    {
      field: "coreFeatures",
      selector: (a) => a.coreFeatures,
      canonicalizer: canonicalFeature,
      resolution: consensus.coreFeatures,
    },
    {
      field: "keyDeliverables",
      selector: (a) => a.keyDeliverables,
      canonicalizer: canonicalDeliverable,
      resolution: consensus.keyDeliverables,
    },
    {
      field: "technicalConsiderations",
      selector: (a) => a.technicalConsiderations,
      canonicalizer: canonicalTechnicalConsideration,
      resolution: consensus.technicalConsiderations,
    },
  ];

  for (const check of arrayChecks) {
    const overlaps: number[] = [];
    for (let i = 0; i < results.length; i++) {
      for (let j = i + 1; j < results.length; j++) {
        overlaps.push(
          calculateOverlap(
            check.selector(results[i].analysis),
            check.selector(results[j].analysis),
            check.canonicalizer,
          ),
        );
      }
    }

    const averageOverlap =
      overlaps.length > 0
        ? overlaps.reduce((sum, value) => sum + value, 0) / overlaps.length
        : 1;

    if (averageOverlap < 0.6) {
      conflicts.push({
        field: check.field,
        values: results.map((r) => ({
          model: r.model,
          value: check.selector(r.analysis),
        })),
        resolution: check.resolution,
        reason: `Model overlap for ${check.field} was ${Math.round(averageOverlap * 100)}%, so the values were normalized and resolved into a canonical set.`,
      });
    }
  }

  return conflicts;
}

function calculateModelAgreementScore(
  model: ProjectAnalysis,
  consensus: ProjectAnalysis,
): number {
  const scores = [
    calculateOverlap(model.coreFeatures, consensus.coreFeatures, canonicalFeature),
    calculateOverlap(model.requiredSkills, consensus.requiredSkills, canonicalSkill),
    calculateOverlap(model.keyDeliverables, consensus.keyDeliverables, canonicalDeliverable),
    calculateOverlap(
      model.technicalConsiderations,
      consensus.technicalConsiderations,
      canonicalTechnicalConsideration,
    ),
    model.complexity === consensus.complexity ? 1 : 0,
    model.experienceLevel === consensus.experienceLevel ? 1 : 0,
    model.budgetAssessment === consensus.budgetAssessment ? 1 : 0,
    model.timelineAssessment === consensus.timelineAssessment ? 1 : 0,
  ];

  // Features and skills matter most for downstream freelancer matching.
  const weights = [0.2, 0.25, 0.1, 0.1, 0.1, 0.1, 0.075, 0.075];
  return scores.reduce((sum, score, index) => sum + score * weights[index], 0);
}

/* ============================================================
   CONSENSUS CALCULATION
   ============================================================ */

function calculateProjectConsensus(
  results: ProjectAnalysisModelResult[],
  requirements: ProjectAssistantRequirements,
): ProjectAnalysisConsensus {
  if (results.length === 0) {
    throw new Error(
      "Cannot calculate Project Analysis consensus without model results",
    );
  }

  const analyses = results.map((result) => result.analysis);

  const projectTitle = chooseMajorityString(analyses.map((item) => item.projectTitle));
  const projectDescription = chooseMajorityString(
    analyses.map((item) => item.projectDescription),
  );
  const projectType = chooseMajorityString(analyses.map((item) => item.projectType));

  const platformValues = analyses
    .map((item) => item.platform)
    .filter((value): value is string => value !== null);

  const platform = platformValues.length > 0 ? chooseMajorityString(platformValues) : null;

  const targetUsers = mergeStringArrays(analyses.map((item) => item.targetUsers));
  const coreFeatures = mergeStringArrays(
    analyses.map((item) => item.coreFeatures),
    canonicalFeature,
  );
  const complexity = chooseComplexity(analyses.map((item) => item.complexity));
  const requiredSkills = mergeStringArrays(
    analyses.map((item) => item.requiredSkills),
    canonicalSkill,
  );
  const experienceLevel = chooseExperienceLevel(
    analyses.map((item) => item.experienceLevel),
  );
  const keyDeliverables = mergeStringArrays(
    analyses.map((item) => item.keyDeliverables),
    canonicalDeliverable,
  );
  const technicalConsiderations = mergeStringArrays(
    analyses.map((item) => item.technicalConsiderations),
    canonicalTechnicalConsideration,
  );

  // The client-approved budget and timeline are authoritative.
  // Project Analysis assesses them but must never silently change them.
  const budget = requirements.budget;
  const budgetAssessment = chooseMajorityString(
    analyses.map((item) => item.budgetAssessment),
  ) as BudgetAssessment;
  const estimatedTimelineDays = requirements.timeline.days;
  const timelineAssessment = chooseMajorityString(
    analyses.map((item) => item.timelineAssessment),
  ) as TimelineAssessment;

  const milestones = buildSemanticMilestoneConsensus(results, budget);

  const consensusAnalysis: ProjectAnalysis = {
    projectTitle,
    projectDescription,
    projectType,
    platform,
    targetUsers,
    coreFeatures,
    complexity,
    requiredSkills,
    experienceLevel,
    keyDeliverables,
    technicalConsiderations,
    budget,
    budgetAssessment,
    estimatedTimelineDays,
    timelineAssessment,
    milestones,
  };

  const conflicts = detectConflicts(results, consensusAnalysis);
  const hasConflict = conflicts.length > 0;

  const agreementScores = results.map((result) =>
    calculateModelAgreementScore(result.analysis, consensusAnalysis),
  );

  const averageAgreement =
    agreementScores.reduce((sum, score) => sum + score, 0) /
    agreementScores.length;

  const agreementThreshold = 0.8;
  const agreementCount = agreementScores.filter(
    (score) => score >= agreementThreshold,
  ).length;

  let resolutionMethod: AnalysisResolutionMethod = "CONSENSUS";

  if (!hasConflict) {
    resolutionMethod = "CONSENSUS";
  } else if (agreementCount >= Math.ceil(results.length / 2)) {
    resolutionMethod = "MAJORITY";
  } else {
    resolutionMethod = "RESOLVED";
  }

  let confidence: "LOW" | "MEDIUM" | "HIGH";

  // HIGH requires all models to independently align strongly with the
  // final consensus. A small isolated conflict does not automatically
  // force LOW confidence if the overall agreement remains strong.
  if (
    results.length >= 2 &&
    agreementCount === results.length &&
    averageAgreement >= 0.8
  ) {
    confidence = "HIGH";
  } else if (averageAgreement >= 0.65 && agreementCount >= Math.ceil(results.length / 2)) {
    confidence = "MEDIUM";
  } else {
    confidence = "LOW";
    if (averageAgreement < 0.5) {
      resolutionMethod = "UNRESOLVED";
    }
  }

  const roundedAgreement = Math.round(averageAgreement * 100);

  const reasoning = hasConflict
    ? `Project Analysis reached ${roundedAgreement}% average model agreement. ${agreementCount}/${results.length} model(s) strongly aligned with the final consensus. ${conflicts.length} field conflict(s) were detected and ${resolutionMethod.toLowerCase()}.`
    : `All ${results.length} model(s) produced compatible project analyses with ${roundedAgreement}% average agreement and no material conflicts.`;

  return {
    analysis: consensusAnalysis,
    agreementCount,
    totalModels: results.length,
    confidence,
    hasConflict,
    conflicts,
    resolutionMethod,
    reasoning,
  };
}

/* ============================================================
   MAIN PROJECT ANALYSIS ENTRY POINT
   ============================================================ */

export async function analyzeProject(
  requirements: ProjectAssistantRequirements,
): Promise<ProjectAnalysisResult> {
  if (!requirements || typeof requirements !== "object") {
    throw new Error("Project Assistant requirements are required");
  }

  if (!requirements.projectTitle?.trim()) {
    throw new Error("Project title is required");
  }

  if (!requirements.description?.trim()) {
    throw new Error("Project description is required");
  }

  if (!Array.isArray(requirements.coreFeatures)) {
    throw new Error("Project core features are required");
  }

  if (
    !requirements.budget ||
    typeof requirements.budget.amount !== "number" ||
    !Number.isFinite(requirements.budget.amount) ||
    requirements.budget.amount <= 0
  ) {
    throw new Error("Approved project budget is required");
  }

  if (
    !requirements.timeline ||
    typeof requirements.timeline.days !== "number" ||
    !Number.isInteger(requirements.timeline.days) ||
    requirements.timeline.days <= 0
  ) {
    throw new Error("Approved project timeline is required");
  }

  // Fallback to configured models or the shared GONKA_MODELS constants.
  const envModels = process.env.GONKA_MODELS?.split(",")
    .map((m) => m.trim())
    .filter(Boolean);

  const configuredDefaults = GONKA_MODELS.filter(
    (value) => typeof value === "string" && value.trim().length > 0,
  );

  const models =
    envModels && envModels.length > 0
      ? envModels
      : configuredDefaults.length > 0
        ? configuredDefaults
        : [
            "deepseek-ai/DeepSeek-V4-Flash-0731",
            "MiniMaxAI/MiniMax-M2.7",
          ];

  console.log(`Running ${models.length} Project Analysis models in parallel...`);

  const execution = await runAcrossModels(models, (model) =>
    analyzeProjectWithGonka(requirements, model),
  );

  const successfulResults = execution.results.filter(
    (
      result,
    ): result is typeof result & {
      success: true;
      result: ProjectAnalysisModelResult;
    } => result.success && result.result !== undefined,
  );

  if (successfulResults.length === 0) {
    throw new Error("All Gonka models failed Project Analysis");
  }

  const modelResults = successfulResults.map((result) => result.result);
  const consensus = calculateProjectConsensus(modelResults, requirements);

  return {
    analysis: consensus.analysis,
    consensus,
    modelResults,
    successfulModels: successfulResults.length,
    failedModels: execution.results.filter((result) => !result.success).length,
  };
}