import json
import os
import re
from pathlib import Path

from dotenv import load_dotenv
from gitingest import ingest


# ============================================================
# CONFIGURATION
# ============================================================

load_dotenv(".env.local")

REPO_URL = "https://github.com/404notfound-j/Travooli_System.git"

GITHUB_PAT = os.getenv("GITHUB_PAT")

OUTPUT_FILE = Path(__file__).parent / ".gitingest-evidence.json"

# For this first test, we manually define the files relevant
# to the login milestone.
RELEVANT_FILES = [
    "signIn.php",
    "signUp.php",
    "connection.php",
    "js/sign.js",
]


# ============================================================
# VALIDATION
# ============================================================

if not GITHUB_PAT:
    raise RuntimeError("Missing GITHUB_PAT in .env.local")


# ============================================================
# FILE EXTRACTION
# ============================================================

def extract_file(content: str, filename: str):
    """
    Extract the complete file block generated by Gitingest.
    """

    pattern = (
        r"={48}\n"
        r"FILE:\s*" + re.escape(filename) + r"\n"
        r"={48}\n"
        r"(.*?)"
        r"(?=\n={48}\nFILE:|\Z)"
    )

    match = re.search(
        pattern,
        content,
        re.DOTALL,
    )

    if not match:
        return None

    return (
        f"FILE: {filename}\n\n"
        f"{match.group(1).strip()}"
    )

# ============================================================
# MAIN
# ============================================================

def main():
    print("=" * 60)
    print("GITINGEST — PRIVATE REPOSITORY EVIDENCE")
    print("=" * 60)

    print(f"Repository: {REPO_URL}")
    print("PAT: Loaded")

    print("\nIngesting private repository...\n")

    summary, tree, content = ingest(
        REPO_URL,
        token=GITHUB_PAT,
    )

    print("✓ Private repository accessed")

    selected_files = {}
    missing_files = []

    for filename in RELEVANT_FILES:
        file_content = extract_file(content, filename)

        if file_content:
            selected_files[filename] = file_content
            print(f"✓ Selected: {filename}")
        else:
            missing_files.append(filename)
            print(f"⚠ Not found: {filename}")

    if not selected_files:
        raise RuntimeError(
            "No relevant files were found in the Gitingest digest."
        )

    evidence = "\n\n".join(
        selected_files.values()
    )

    output = {
        "repository": REPO_URL,
        "summary": summary,
        "selected_files": list(selected_files.keys()),
        "missing_files": missing_files,
        "evidence": evidence,
        "evidence_size": len(evidence),
    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            output,
            file,
            indent=2,
            ensure_ascii=False,
        )

    print("\n" + "=" * 60)
    print("GITINGEST RESULT")
    print("=" * 60)

    print(f"Files selected : {len(selected_files)}")
    print(f"Evidence size  : {len(evidence):,} characters")
    print(f"Output file    : {OUTPUT_FILE}")

    print("\n✓ Gitingest evidence prepared")
    print("✓ Ready for Gonka")


if __name__ == "__main__":
    main()